function s_drawSigLine_2wave_RSFC(axes,h_bar1,h_bar2,tmpRes)
% By Kunru Song 2022.9.29

%% Two group difference
% Idx1 Time0 - Idx2 Time0
if h_bar1.YData(1) >0 && h_bar2.YData(1)>0
    y_t0 = max([h_bar1.YData(1) h_bar2.YData(1)]);
    y_bias = ( abs(axes.YLim(end)) - abs(y_t0) )/3;
elseif h_bar1.YData(1) <0 && h_bar2.YData(1)<0
    y_t0 = min([h_bar1.YData(1) h_bar2.YData(1)]);
    y_bias = -( abs(axes.YLim(1)) - abs(y_t0) )/3;
end
X_left = h_bar1.XEndPoints(1);
X_right = h_bar2.XEndPoints(1);
draw_GroupDiffLine(axes,X_left,X_right,y_t0,y_bias)
add_text_star(axes,tmpRes,'Idx2Time0-Idx1Time0',X_left,X_right,y_t0,y_bias)
%%
% Idx1 Time1 - Idx2 Time1
if h_bar1.YData(2) >0 && h_bar2.YData(2)>0
    y_t1 = max([h_bar1.YData(2) h_bar2.YData(2)]);
    y_bias = ( abs(axes.YLim(end)) - abs(y_t1) )/3;
elseif h_bar1.YData(2) <0 && h_bar2.YData(2)<0
    y_t1 = min([h_bar1.YData(2) h_bar2.YData(2)]);
    y_bias = -( abs(axes.YLim(1)) - abs(y_t1) )/3;
end
X_left = h_bar1.XEndPoints(2);
X_right = h_bar2.XEndPoints(2);
draw_GroupDiffLine(axes,X_left,X_right,y_t1,y_bias)
add_text_star(axes,tmpRes,'Idx2Time1-Idx1Time1',X_left,X_right,y_t1,y_bias)

end
%% subfunctions
function draw_GroupDiffLine(axes,X_left,X_right,y,y_bias)
if y>0
line(axes,...
    [X_left X_right],...
    [y+y_bias y+y_bias],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [X_left X_left],...
    [y+y_bias-y_bias/4 y+y_bias],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [X_right X_right],...
    [y+y_bias-y_bias/4 y+y_bias],...
    'Color','black',...
    'LineWidth',1.5)
else
    line(axes,...
    [X_left X_right],...
    [y+y_bias y+y_bias],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [X_left X_left],...
    [y+y_bias-y_bias/4 y+y_bias],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [X_right X_right],...
    [y+y_bias-y_bias/4 y+y_bias],...
    'Color','black',...
    'LineWidth',1.5)
end
end
function add_text_star(axes,Res_SimpleEffect,ContrastName,X_left,X_right,y,y_bias)
p_text = Res_SimpleEffect.p(strcmp(Res_SimpleEffect.contrast,ContrastName));
p_text = regexprep(p_text,'<|\.|[0-9]','');
if y > 0
    if isempty(p_text{1})
        p_text{1} = 'n.s.';
        text(axes, (X_left + X_right)/2-length(p_text{1})*0.015,...
            y+y_bias+y_bias/2,...
            p_text,'FontSize',10)
    else
        text(axes, (X_left + X_right)/2-length(p_text{1})*0.025,...
            y+y_bias+y_bias/10,...
            p_text,'FontSize',14)
    end
else
    if isempty(p_text{1})
        p_text{1} = 'n.s.';
        text(axes, (X_left + X_right)/2-length(p_text{1})*0.015,...
            y+y_bias+y_bias/6,...
            p_text,'FontSize',10)
    else
        text(axes, (X_left + X_right)/2-length(p_text{1})*0.025,...
            y+y_bias+y_bias/2,...
            p_text,'FontSize',14)
    end
end
end