function s_drawSigLine_2wave(h,h_bar1,h_bar2,axes,SimEffRes)
Y_Name = strrep(axes.Title.String,' Sum Score','');
Res_SimpleEffect = SimEffRes( strcmp(SimEffRes.Y_Name,Y_Name) & SimEffRes.MeaningfulContrastFlag,: );
% Idx1 Time0 - Idx2 Time0
maxy_t0 = max([h_bar2.YData(1) h_bar1.YData(1)]);
line(axes,...
    [h_bar1.XEndPoints(1) h_bar2.XEndPoints(1)],...
    [maxy_t0+0.05 maxy_t0+0.05],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [h_bar1.XEndPoints(1) h_bar1.XEndPoints(1)],...
    [maxy_t0+0.04 maxy_t0+0.05],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [h_bar2.XEndPoints(1) h_bar2.XEndPoints(1)],...
    [maxy_t0+0.04 maxy_t0+0.05],...
    'Color','black',...
    'LineWidth',1.5)
p_text = Res_SimpleEffect.p(strcmp(Res_SimpleEffect.contrast,'Idx2Time0-Idx1Time0'));
p_text = regexprep(p_text,'<|\.|[0-9]','');
if isempty(p_text{1})
    p_text{1} = 'n.s.';
end
text(axes, (h_bar1.XEndPoints(1) + h_bar2.XEndPoints(1))/2-length(p_text{1})*0.03,...
    maxy_t0+0.05+0.005,...
    p_text,'FontSize',14)

% Idx1 Time1 - Idx2 Time1
maxy_t1 = max([h_bar2.YData(2) h_bar1.YData(2)]);
line(axes,...
    [h_bar1.XEndPoints(2) h_bar2.XEndPoints(2)],...
    [maxy_t1+0.05 maxy_t1+0.05],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [h_bar1.XEndPoints(2) h_bar1.XEndPoints(2)],...
    [maxy_t1+0.04 maxy_t1+0.05],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [h_bar2.XEndPoints(2) h_bar2.XEndPoints(2)],...
    [maxy_t1+0.04 maxy_t1+0.05],...
    'Color','black',...
    'LineWidth',1.5)
p_text = Res_SimpleEffect.p(strcmp(Res_SimpleEffect.contrast,'Idx2Time1-Idx1Time1'));
p_text = regexprep(p_text,'<|\.|[0-9]','');
if isempty(p_text{1})
    p_text{1} = 'n.s.';
    text(axes, (h_bar1.XEndPoints(2)+h_bar2.XEndPoints(2))/2-length(p_text{1})*0.02,...
    maxy_t1+0.05+0.015,...
    p_text,'FontSize',10)
else
    text(axes, (h_bar1.XEndPoints(2)+h_bar2.XEndPoints(2))/2-length(p_text{1})*0.03,...
    maxy_t1+0.05+0.005,...
    p_text,'FontSize',14)
end


% Idx2 Time0 - Idx2 Time1
line(axes,...
    [h_bar1.XEndPoints(1) h_bar1.XEndPoints(2)],...
    [h_bar1.YData(1)-0.04 h_bar1.YData(1)-0.04],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [h_bar1.XEndPoints(1) h_bar1.XEndPoints(1)],...
    [h_bar1.YData(1)-0.03 h_bar1.YData(1)-0.04],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [h_bar1.XEndPoints(2) h_bar1.XEndPoints(2)],...
    [h_bar1.YData(1)-0.03 h_bar1.YData(1)-0.04],...
    'Color','black',...
    'LineWidth',1.5)
p_text = Res_SimpleEffect.p(strcmp(Res_SimpleEffect.contrast,'Idx2Time0-Idx2Time1'));
p_text = regexprep(p_text,'<|\.|[0-9]','');
if isempty(p_text{1})
    p_text{1} = 'n.s.';
end
text(axes, (h_bar1.XEndPoints(1)+h_bar1.XEndPoints(2))/2-length(p_text{1})*0.03,...
    h_bar1.YData(1)-0.04-0.015,...
    p_text,'FontSize',14)
% Idx1 Time0 - Idx1 Time1
line(axes,...
    [h_bar2.XEndPoints(1) h_bar2.XEndPoints(2)],...
    [h_bar2.YData(1)+0.09 h_bar2.YData(1)+0.09],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [h_bar2.XEndPoints(1) h_bar2.XEndPoints(1)],...
    [h_bar2.YData(1)+0.08 h_bar2.YData(1)+0.09],...
    'Color','black',...
    'LineWidth',1.5)
line(axes,...
    [h_bar2.XEndPoints(2) h_bar2.XEndPoints(2)],...
    [h_bar2.YData(1)+0.08 h_bar2.YData(1)+0.09],...
    'Color','black',...
    'LineWidth',1.5)
p_text = Res_SimpleEffect.p(strcmp(Res_SimpleEffect.contrast,'Idx2Time0-Idx2Time1'));
p_text = regexprep(p_text,'<|\.|[0-9]','');
if isempty(p_text{1})
    p_text{1} = 'n.s.';
end
text(axes, (h_bar2.XEndPoints(1)+h_bar2.XEndPoints(2))/2-length(p_text{1})*0.03,...
    h_bar2.YData(1)+0.09+0.005,...
    p_text,'FontSize',14)
end