function T_SubG = s_ExtractLongitudinalCell(T_LongitudinalCell,DV_VarName)
% Extract the group mean\sd\se from the longitudinal cell, which is
% generated by user-defined scripts in the folder 'Step_3_Longitudinal'
T_SubG = table('Size',[length(T_LongitudinalCell),2],...
    'VariableTypes',{'cell','cell'},'VariableNames',{'Y_Name','stats'});
for j=1:length(T_LongitudinalCell)
    fprintf('Time waves for DV %s \n',DV_VarName{j})
    tabulate(T_LongitudinalCell{j}.eventname)
    eventname = unique(T_LongitudinalCell{j}.eventname);
    for i=1:length(eventname)
        fprintf('# DV VarName: %s Time Wave:%s\n',DV_VarName{j},eventname{i});
        Y =  T_LongitudinalCell{j}.Y(strcmp(T_LongitudinalCell{j}.eventname,eventname{i}));
        Idx = double(T_LongitudinalCell{j}.Idx(strcmp(T_LongitudinalCell{j}.eventname,eventname{i})));
        if i==1
            stats=s_GetSubGMeanErr(Y,Idx);
            stats.Time=repmat(eventname(i),2,1);
        else
            tmp=s_GetSubGMeanErr(Y,Idx);
            tmp.Time=repmat(eventname(i),2,1);
            stats = [stats;tmp];
        end
    end
    disp(stats)
    T_SubG.stats(j) = {stats};
    T_SubG.Y_Name(j) = DV_VarName(j);
end
disp(T_SubG)
fprintf('Extract longitudinal cells finished!\n')