function beta_NetMatrix = s_GetAdjMatrix_Longitudinal(NetName,PairwiseRSFNC)
% Get the adjancet matrix for ABCD tabulated data RSFNC variables
% By Kunru Song 2021.10
% Input:
% GordonName={'auditory network';'cingulo opercular network';...
%     'cingulo parietal network';'default network';...
%     'dorsal attention network';'fronto parietal network';...
%     'none network';'retrosplenial temporal network';...
%     'sensorimotor hand network';'sensorimotor mouth network';...
%     'salience network';'ventral attention network';'visual network'};
% asegName={'left cerebellum cortex';'left thalamus proper';...
%     'left caudate';'left putamen';'left pallidum';'brain stem';...
%     'left hippocampus';'left amygdala';'left accumbens area';...
%     'left ventraldc';'right cerebellum cortex';'right thalamus proper';...
%     'right caudate';'right putamen';'right pallidum';'right hippocampus';...
%     'right amygdala';'right accumbens area';'right ventraldc'};
% NetName=[GordonName;asegName];

beta_NetMatrix=zeros(length(NetName),length(NetName));

for i=1:size(PairwiseRSFNC,1)
    RowIdx=find(strcmp(NetName,PairwiseRSFNC.Node1(i)));
    ColIdx=find(strcmp(NetName,PairwiseRSFNC.Node2(i)));
    beta_NetMatrix(RowIdx,ColIdx)=PairwiseRSFNC.Estimate(i);
    beta_NetMatrix(ColIdx,RowIdx)=PairwiseRSFNC.Estimate(i);
end
end