clc
clear
%% Preprocessing longitudinal RSFNC data

load ../Res_3_IntermediateData/RSFC_Longitudinal_GroupMainEff.mat
% find the RSFNCs with significant main effect of group
Flag = ismember(compact_data.Properties.VariableNames,Res_RSFNC.RSFC_Name);
RSFNC_values = compact_data(:,Flag);
compact_data.RSfMRI_MeanFD = compact_data.rsfmri_c_ngd_meanmotion;
compact_data = removevars(compact_data,{'rsfmri_c_ngd_meanmotion','imgincl_rsfmri_include'});
MissFlag = ismissing(table(compact_data.Idx,compact_data.eventname,...
    compact_data.baseline_age,compact_data.sex,...
    compact_data.Race_PrntRep,compact_data.Ethnicity_PrntRep,...
    compact_data.ParentsEdu,compact_data.ParentMarital,compact_data.FamilyIncome,...
    compact_data.HouseholdSize,compact_data.HouseholdStructure,...
    compact_data.RSfMRI_MeanFD));
MissFlag = sum(MissFlag,2)~=0;
fprintf('# %d data points have missing values (Total N=%d)\n',...
    sum(MissFlag),size(compact_data,1))
fprintf('List-wise deletion......\n')
compact_data(MissFlag,:)=[];
compact_data = s_preparLongitudinalRSFNC(compact_data);
%% Extract RSFNCs with significant group main effect
Flag = ~contains(compact_data.Properties.VariableNames,'rsfmri_') | ...
    ismember(compact_data.Properties.VariableNames,Res_RSFNC.RSFC_Name);
compact_data = compact_data(:,Flag);
% saved_data = compact_data(:,...
%     ~(contains(compact_data.Properties.VariableNames,'CBCL_') | ...
%     contains(compact_data.Properties.VariableNames,'PPS_') | ...
%     contains(compact_data.Properties.VariableNames,'UPPS_') | ...
%     contains(compact_data.Properties.VariableNames,'BIS_') | ...
%     contains(compact_data.Properties.VariableNames,'BAS_') | ...
%     contains(compact_data.Properties.VariableNames,'NIHTB_') | ...
%     contains(compact_data.Properties.VariableNames,'weekday_') | ...
%     contains(compact_data.Properties.VariableNames,'weekend_') | ...
%     contains(compact_data.Properties.VariableNames,'screen_') | ...
%     contains(compact_data.Properties.VariableNames,'PLE_'))    );
% writetable(saved_data,'../Res_3_IntermediateData/RSFC_GroupMainEffSig.xlsx')
% Extract Simple Effect Analyses Results
Std_GroupMainEff = readtable('../Res_2_Results/Table_S15.xlsx');
SimEffRes = readtable('../Res_2_Results/Table_S16.xlsx');
SimEffRes = SimEffRes(SimEffRes.MeaningfulContrastFlag==1,:);
%% Plot Figure S18
eventname = unique(compact_data.eventname);
h=figure();
Res_RSFNC = sortrows(Res_RSFNC,'Estimate','descend');
set(h,'Position',[0 0 1920 1080])
for i=1:size(Res_RSFNC,1)
    for j=1:length(eventname)
        Idx = double(compact_data.Idx(strcmp(compact_data.eventname,eventname{j})));
        Idx = Idx - 1; Idx(Idx==0) = 2;
        tabulate(Idx)
        Y_Name = Res_RSFNC.RSFC_Name{i};
        Y = compact_data{strcmp(compact_data.eventname,eventname{j}),strcmp(compact_data.Properties.VariableNames,Y_Name)};
         if j==1
            stats=s_GetSubGMeanErr_Raw(Y,Idx);
            stats.Time=repmat(eventname(j),2,1);
        else
            tmp=s_GetSubGMeanErr_Raw(Y,Idx);
            tmp.Time=repmat(eventname(j),2,1);
            stats = [stats;tmp];
        end
    end
    subplot(4,4,i)
    s_BarPlot_RSFNC(stats)
    title_text = strcat(Res_RSFNC.Node1(i), '-', Res_RSFNC.Node2(i));
    title_text = replace(title_text,...
        {'auditory network';'cingulo opercular network';...
    'cingulo parietal network';'default network';...
    'dorsal attention network';'fronto parietal network';...
    'none network';'retrosplenial temporal network';...
    'sensorimotor hand network';'sensorimotor mouth network';...
    'salience network';'ventral attention network';'visual network';...
    'left cerebellum cortex';'left thalamus proper';...
    'left caudate';'left putamen';'left pallidum';'brain stem';...
    'left hippocampus';'left amygdala';'left accumbens area';...
    'left ventraldc';'right cerebellum cortex';'right thalamus proper';...
    'right caudate';'right putamen';'right pallidum';'right hippocampus';...
    'right amygdala';'right accumbens area';'right ventraldc'},...
    {'AuN';'CON';...
    'CPN';'DMN';...
    'DAN';'FPN';...
    'none';'RsTN';...
    'SmHN';'SmMN';...
    'SN';'VAN';'ViN';...
    'cerebellum_L';'thalamus_L';...
    'caudate_L';'putamen_L';'pallidum_L';'brain stem';...
    'hippocampus_L';'amygdala_L';'accumbens_L';...
    'ventraldc_L';'cerebellum_R';'thalamus_R';...
    'caudate_R';'putamen_R';'pallidum_R';'hippocampus_R';...
    'amygdala_R';'accumbens_R';'ventraldc_R'});
    if Res_RSFNC.Estimate(i) > 0
        title(title_text,'Color',[1.0000    0.1875         0])
    else
        title(title_text,'Color',[0.2118    0.7882    1.0000])
    end
    tmpRes = SimEffRes(strcmp(SimEffRes.Y_Name,Res_RSFNC.RSFC_Name(i)),:);
    axes = h.Children(1);
    h_bar1 = axes.Children(4);
    h_bar2 = axes.Children(3);
    s_drawSigLine_2wave_RSFC(axes,h_bar1,h_bar2,tmpRes)
%     set(gca,'YLim',[-0.5 1.5])
end
print('../Res_2_Results/Figure_S18','-dtiff','-r300')
print('../Res_2_Results/Figure_S18','-dsvg','-r300')
close(h)





