clc
clear
diary ../Res_1_Logs/Log_CrossSectional_stat_3.txt

% for Table S6: logistic regression analysis for demographic data
load ..\Res_3_IntermediateData\ABCD4.0_Recoded_Baseline_Demo_Behav.mat
load ..\Res_3_IntermediateData\ABCD4.0_Demo_MissFlag.mat
% for ABCD 4.0 baseline wave data table
%% clean data (list-wise deletion)
MissFlag.Idx_MissFlag = isnan(double(Demograph.Idx));
MissFlag = removevars(MissFlag,{'Edu_MissFlag','PrntEmp_MissFlag'});
Demo_MissFlag = sum(MissFlag.Variables,2)~=0;
fprintf('# %d subjects have missing values in demographics at baseline\n',sum(Demo_MissFlag));
fprintf('Included demographics:\n')
disp(strrep(MissFlag.Properties.VariableNames,'_MissFlag',''))
fprintf('Missing number in the demographic variables\n')
disp([strrep(MissFlag.Properties.VariableNames,'_MissFlag','');num2cell(sum(MissFlag.Variables))])
fprintf('Notes: interview_age, sex, ethnicity and handedness don have missing values\n ')
tabulate(Demograph.Idx)
Demograph=Demograph(~Demo_MissFlag,:);
fprintf('# %d subjects left after list-wise deletion\n',size(Demograph,1));
Demograph.Idx = double(Demograph.Idx)-1; %Reference: SMA Subgroup 2
Demograph = s_zscoreDemo(Demograph);
%% Generalized LME (GLME) modeling
mdl=fitglme(Demograph,...
    ['Idx~interview_age+sex+Race_PrntRep+Ethnicity_PrntRep+Relationship',...
    '+Handedness+ParentsEdu+ParentMarital+HouseholdSize+HouseholdStructure',...
    '+BirthCountry+FamilyIncome+(1|site_id_l)+(1|site_id_l:FamilyID)'],...
    'Distribution','Binomial','FitMethod','REMPL',...
    'CheckHessian',true,...
    'CovariancePattern',{'Diagonal','Diagonal'},...
    'InitPLIterations',100,...
    'PLIterations',300,...
    'Optimizer','fminsearch',...
    'UseSequentialFitting',true,...
    'Verbos',0);
disp(mdl)
%% Reorganize and save the result of GLME
Res_LogitCoef=dataset2table(mdl.Coefficients);
Res_LogitCoef.N = mdl.NumObservations*ones(17,1);
Res_LogitCoef.Exp_B=exp(mdl.Coefficients.Estimate);
Res_LogitCoef.CI95 = cellstr(strcat(...
    num2str(round(Res_LogitCoef.Estimate,3),'%1.3f'),...
    ' [',...
    num2str(round(Res_LogitCoef.Lower,3),['%1.' num2str(3) 'f']),...
    ', ',...
    num2str(round(Res_LogitCoef.Upper,3),['%1.' num2str(3) 'f']),...
    ']'));
Res_LogitCoef = movevars(Res_LogitCoef,'CI95','Before','SE');
writetable(Res_LogitCoef,...
    '..\Res_2_Results\Table_S6.xlsx');
diary off

