clc
clear
%% Organize the Longitudinal Analysis Results about behavioral measures
MdlFileList = {'../Res_3_IntermediateData/totprob_LME_R_summary.doc',...
    '../Res_3_IntermediateData/PPS_LME_R_summary.doc',...
    '../Res_3_IntermediateData/UPPS_LME_R_summary.doc',...
    '../Res_3_IntermediateData/BIS_LME_R_summary.doc',...
    '../Res_3_IntermediateData/BAS_LME_R_summary.doc',...
    };
EmmFileList = {'../Res_3_IntermediateData/totprob_EMM_R_contrast.doc',...
    '../Res_3_IntermediateData//PPS_EMM_R_contrast.doc',...
    '../Res_3_IntermediateData/UPPS_EMM_R_contrast.doc',...
    '../Res_3_IntermediateData/BIS_EMM_R_contrast.doc',...
    '../Res_3_IntermediateData/BAS_EMM_R_contrast.doc',...
    };
%% Organize the R ouput doc file for LME Summary
% Organize the Standardized LME results
Res = cell(length(MdlFileList),1);
for i=1:length(MdlFileList)
   Res{i}  = s_ExtractLMEsummary(MdlFileList{i});
   [~,filename,~] = fileparts(MdlFileList{i});
   Y_Name = strrep(filename,'_LME_R_summary','');
   Res{i}.Y_Name = repmat(cellstr(Y_Name),size(Res{i},1),1);
end
Res = vertcat(Res{:});
Res = movevars(Res,'Y_Name','Before','Name');
Res.std_beta_num = str2double(strrep(strrep(Res.std_beta,'*',''),'–','-'));
disp(Res)
writetable(Res,'../Res_2_Results/Table_S11_StandardizedBeta.xlsx')
%% Organize the R ouput doc file for EMM contrast
% Organize the simple effect analyses results for LME models
Res = cell(length(MdlFileList),1);
for i=1:length(EmmFileList)
   Res{i}  = s_ExtractEmmeansRes(EmmFileList{i});
   [~,filename,~] = fileparts(EmmFileList{i});
   Y_Name = strrep(filename,'_EMM_R_contrast','');
   Res{i}.Y_Name = repmat(cellstr(Y_Name),size(Res{i},1),1);
end
Res = vertcat(Res{:});
Res = movevars(Res,'Y_Name','Before','rownum');
Res.Comparison = strrep(...
    strrep(...
    strrep(...
    strrep(...
    strrep(Res.contrast,'Idx1','G1:'),...
    'Idx2','G2:'),...
    'Time0','T0'),...
    'Time1','T1'),...
    'Time2','T2');
Res.MeaningfulContrastFlag = double(~(strcmp(Res.contrast,'Idx2Time0-Idx1Time1') |...
    strcmp(Res.contrast,'Idx1Time0-Idx2Time1') |...
    strcmp(Res.contrast,'Idx2Time1-Idx1Time2') |...
    strcmp(Res.contrast,'Idx1Time2-Idx2Time1') |...
    strcmp(Res.contrast,'Idx2Time1-Idx1Time2') |...
    strcmp(Res.contrast,'Idx1Time0-Idx2Time2') |...
    strcmp(Res.contrast,'Idx1Time1-Idx2Time2') |...
    strcmp(Res.contrast,'Idx2Time0-Idx1Time2')));
disp(Res)
writetable(Res,'../Res_2_Results/Table_S12.xlsx')
