clc
clear
diary ../Res_1_Logs/Log_Longitudinal_stat_5.txt
fprintf('Extract the significant main effect of SMA subgroups for RSFC LME analysis results\n')
Res_RSFNC = readtable(...
    '..\Res_2_Results\Table_LongitudinalRSFNC.xlsx');
RSFNC_Interaction = Res_RSFNC(strcmp(Res_RSFNC.Name,'Time:Idx_1'),:);
RSFNC_MainEff_Time = Res_RSFNC(strcmp(Res_RSFNC.Name,'Time'),:);
RSFNC_MainEff_Idx = Res_RSFNC(strcmp(Res_RSFNC.Name,'Idx_1'),:);
%% Display the summary of longitudinal RSFNC LME results
fprintf('========================================================================\n')
fprintf('# RSFNC Interaction Effect: # %d FCs uncorrected-p<0.05  # %d FCs FDR-corrected p<0.05\n',...
    sum(RSFNC_Interaction.pValue < 0.05),sum(RSFNC_Interaction.FDR_pvals < 0.05));
fprintf('# RSFNC Time Main Effect: # %d FCs uncorrected-p<0.05  # %d FCs FDR-corrected p<0.05\n',...
    sum(RSFNC_MainEff_Time.pValue < 0.05),sum(RSFNC_MainEff_Time.FDR_pvals < 0.05));
fprintf('# RSFNC Idx Main Effect: # %d FCs uncorrected-p<0.05  # %d FCs FDR-corrected p<0.05\n',...
    sum(RSFNC_MainEff_Idx.pValue < 0.05),sum(RSFNC_MainEff_Idx.FDR_pvals < 0.05));
fprintf('========================================================================\n')
fprintf('Significant RSFCs in Main effect of SMA subgroup\n')
disp(RSFNC_MainEff_Idx{RSFNC_MainEff_Idx.FDR_pvals < 0.05,1:3})
%% Extract and save the longitudinal group main effct significant RSFC
clearvars Res_RSFNC RSFNC_MainEff_Time RSFNC_Interaction
compact_data = s_Preproc_LongitudinalRSFNC();
Flag = RSFNC_MainEff_Idx.FDR_pvals < 0.05;
Res_RSFNC = RSFNC_MainEff_Idx (Flag,:);
GordonName={'auditory network';'cingulo opercular network';...
    'cingulo parietal network';'default network';...
    'dorsal attention network';'fronto parietal network';...
    'none network';'retrosplenial temporal network';...
    'sensorimotor hand network';'sensorimotor mouth network';...
    'salience network';'ventral attention network';'visual network'};
asegName={'left cerebellum cortex';'left thalamus proper';...
    'left caudate';'left putamen';'left pallidum';'brain stem';...
    'left hippocampus';'left amygdala';'left accumbens area';...
    'left ventraldc';'right cerebellum cortex';'right thalamus proper';...
    'right caudate';'right putamen';'right pallidum';'right hippocampus';...
    'right amygdala';'right accumbens area';'right ventraldc'};
NetName=[GordonName;asegName];
beta_NetMatrix = s_GetAdjMatrix_Longitudinal(NetName,Res_RSFNC);
GordonName={'AuN';'CON';...
    'CPN';'DMN';...
    'DAN';'FPN';...
    'none';'RsTN';...
    'SmHN';'SmMN';...
    'SN';'VAN';'ViN'};
asegName={'cerebellum_L';'thalamus_L';...
    'caudate_L';'putamen_L';'pallidum_L';'brain stem';...
    'hippocampus_L';'amygdala_L';'accumbens_L';...
    'ventraldc_L';'cerebellum_R';'thalamus_R';...
    'caudate_R';'putamen_R';'pallidum_R';'hippocampus_R';...
    'amygdala_R';'accumbens_R';'ventraldc_R'};
NetName=[GordonName;asegName];
save ../Res_3_IntermediateData/RSFC_Longitudinal_GroupMainEff.mat Res_RSFNC beta_NetMatrix NetName compact_data
% find the RSFNCs with significant main effect of group
Flag = ismember(compact_data.Properties.VariableNames,Res_RSFNC.RSFC_Name);
RSFNC_values = compact_data(:,Flag);
compact_data.RSfMRI_MeanFD = compact_data.rsfmri_c_ngd_meanmotion;
compact_data = removevars(compact_data,{'rsfmri_c_ngd_meanmotion','imgincl_rsfmri_include'});
MissFlag = ismissing(table(compact_data.Idx,compact_data.eventname,...
    compact_data.baseline_age,compact_data.sex,...
    compact_data.Race_PrntRep,compact_data.Ethnicity_PrntRep,...
    compact_data.ParentsEdu,compact_data.ParentMarital,compact_data.FamilyIncome,...
    compact_data.HouseholdSize,compact_data.HouseholdStructure,...
    compact_data.RSfMRI_MeanFD));
MissFlag = sum(MissFlag,2)~=0;
fprintf('# %d data points have missing values (Total N=%d)\n',...
    sum(MissFlag),size(compact_data,1))
fprintf('List-wise deletion......\n')
compact_data(MissFlag,:)=[];
compact_data = s_preparLongitudinalRSFNC(compact_data);
%% Extract RSFNCs with significant group main effect
Flag = ~contains(compact_data.Properties.VariableNames,'rsfmri_') | ...
    ismember(compact_data.Properties.VariableNames,Res_RSFNC.RSFC_Name);
compact_data = compact_data(:,Flag);
saved_data = compact_data(:,...
    ~(contains(compact_data.Properties.VariableNames,'CBCL_') | ...
    contains(compact_data.Properties.VariableNames,'PPS_') | ...
    contains(compact_data.Properties.VariableNames,'UPPS_') | ...
    contains(compact_data.Properties.VariableNames,'BIS_') | ...
    contains(compact_data.Properties.VariableNames,'BAS_') | ...
    contains(compact_data.Properties.VariableNames,'NIHTB_') | ...
    contains(compact_data.Properties.VariableNames,'weekday_') | ...
    contains(compact_data.Properties.VariableNames,'weekend_') | ...
    contains(compact_data.Properties.VariableNames,'screen_') | ...
    contains(compact_data.Properties.VariableNames,'PLE_'))    );
writetable(saved_data,'../Res_3_IntermediateData/RSFC_GroupMainEffSig.xlsx')
diary off